Feature/trip details car
WildCodeSchool/2022-09-Orleans-CDA-Projet-KaraoCar pull request #106
Opened 2023-02-13 15:59 UTC by Ysedda

2023-02-13 16:05 UTC, MGliem submitted a review, later dismissed

2023-02-13 16:22 UTC, YDrogen requested changes

2023-02-13 16:22 UTC, YDrogen commented on apps/frontend/web/src/components/search-trip/TripDetails.tsx
> +                            />{' '}
```suggestion
                            />
```

2023-02-13 16:22 UTC, YDrogen commented on apps/frontend/web/src/components/search-trip/TripSummary.tsx
> +                  {trip.driver?.cars[0].brand ?? 'Brand'} -{' '}
```suggestion
                  {trip.driver?.cars[0].brand ?? 'Brand'} -
```

2023-02-13 19:22 UTC, MGliem approved these changes

2023-02-14 08:05 UTC, YDrogen approved these changes

2023-02-14 08:05 UTC, merged