Feature/ci prep
WildCodeSchool/2022-09-Orleans-CDA-Projet-KaraoCar pull request #16
Opened 2022-12-14 12:37 UTC by MGliem

2022-12-14 15:42 UTC, Ysedda approved these changes

2022-12-15 08:08 UTC, YDrogen requested changes

2022-12-15 08:08 UTC, YDrogen commented on .github/workflows/prod-client.yml
> +      - uses: docker/build-push-action@v3
Il faudrait fusionner déplacer ce bloc dans l'autre workflow (ou inversement). 1 seul workflow pour la prod

2022-12-15 08:08 UTC, YDrogen commented on .github/workflows/staging-client.yml
> +      - uses: docker/build-push-action@v3
Idem ici

2022-12-15 10:58 UTC, Ysedda approved these changes

2022-12-15 15:43 UTC, YDrogen approved these changes

2022-12-15 15:43 UTC, merged