Feature/homepage
WildCodeSchool/2022-09-Orleans-CDA-Projet-KaraoCar pull request #25
Opened 2022-12-31 16:39 UTC by MGliem

Fully responsive.
There is a placeholder for the searchbar wich is in another us.

2022-12-31 18:11 UTC, epereira commented on apps/frontend/web/src/pages/Home.tsx
> +            'Lorem ipsum dolor sit ame consectetur adipiscing elit, sed do adipiscing elit, consectetur adipiscing elit'
je ne sais pas si on peut laisser du lorem ipsum, dans la PR ? on peut essayer d'utiliser chatGPT pour rédiger de faux avis, vous en pensez quoi ?

2022-12-31 18:51 UTC, epereira commented on apps/frontend/web/src/pages/Home.tsx
> +        backgroundColor={'#394E61'}
les couleurs en dur est-ce une bonne idée ?

2023-01-04 15:11 UTC, Ysedda commented on apps/frontend/web/src/pages/Home.tsx
> +        backgroundColor={'#394E61'}
Le thème intégrant les couleurs est dans ma PR, faudra simplement faire un fix

2023-01-04 15:19 UTC, Ysedda requested changes
Visuel :
    -  Trop d'espacement dans les premières cartes entre le titre et le body 
    -  Manque de marge sur les cartes en bas de page 
    -  Trop d'espacement autour de "They've adopted it" et/ou remonter l'image
    -  (reponsive only) Le texte de la div centrale ("Traveling without...") manque de marge à gauche

2023-01-06 09:39 UTC, Ysedda approved these changes

2023-01-06 15:12 UTC, DangirasH approved these changes

2023-01-09 08:22 UTC, YDrogen approved these changes

2023-01-09 08:22 UTC, merged