Feature/user connection01
WildCodeSchool/2022-09-Orleans-CDA-Projet-KaraoCar pull request #27
Opened 2023-01-01 16:20 UTC by DangirasH

2023-01-03 16:32 UTC, MGliem requested changes
- Pas mal de nom de commit qui ne vont pas https://www.conventionalcommits.org/en/v1.0.0/ tous les commits ne sont pas forcement des feat, ca peut être aussi des chore, style, etc... Il manque les ":" à chaque fois et certains commit n'ont pas aucun des deux.
- Nom de branch: pourquoi 01?


---------------------------------back-------------------------------

- La structure de dossier dans le back n'est pas bonne. Inspire toi du "nest g resource".
- il manque la migration


------------------------------- Front ----------------------------------

-Il manque le responsive
-Sur le register, du padding dans les inputs

2023-01-03 16:32 UTC, MGliem commented on apps/backend/api/src/auth/constants.ts
> +  secret: 'secretKey',
Comme dit avant, ne pas créer un fichier avec ca ici.

2023-01-03 16:32 UTC, MGliem commented on apps/backend/api/src/main.ts
> +  app.enableCors({ origin: 'http://localhost:5173' });
Si c'est bien fait en front on a pas besoin de cors

2023-01-03 16:32 UTC, MGliem commented on apps/backend/api/src/auth/auth.module.ts
> +      provide: 'AUTH_SERVICE',
On a pas vu comme ca en cours. on fait juste providers: [NomDuService]

2023-01-03 16:32 UTC, MGliem commented on apps/backend/api/src/auth/jwt.strategy.ts
> +      secretOrKey: jwtConstants.secret,
idem (secrets visible sur github)

2023-01-03 16:32 UTC, MGliem commented on apps/backend/api/src/auth/services/auth/auth.service.ts
> +    console.log('coucou');
coucou :)

2023-01-03 16:32 UTC, MGliem commented on apps/backend/api/src/auth/services/auth/auth.service.ts
> +    console.log(userDB, 'user', password);
console log

2023-01-03 16:32 UTC, MGliem commented on apps/backend/api/src/auth/services/auth/auth.service.ts
> +    console.log(matched);
console log

2023-01-03 16:32 UTC, MGliem commented on apps/backend/api/src/auth/utils/LocalStrategy.ts
> +    console.log(user, 'coucou');
coucou :)

2023-01-03 16:32 UTC, MGliem commented on apps/backend/api/src/typeorm/User.ts
> +    name: 'user_id',
user_id ?

2023-01-03 16:32 UTC, MGliem commented on apps/backend/api/src/typeorm/User.ts
> +    type: 'bigint',
On va avoir plus de  2147483647 users ?

2023-01-03 16:32 UTC, MGliem commented on apps/backend/api/src/typeorm/User.ts
> +    default: '',
bizarre de mettre une string vide par defaut mais nullable false

2023-01-03 16:32 UTC, MGliem commented on apps/backend/api/src/typeorm/User.ts
> +    default: '',
idem

2023-01-03 16:32 UTC, MGliem commented on apps/backend/api/src/typeorm/User.ts
> +    name: 'email',
le name: ne sert pas non ?

2023-01-03 16:32 UTC, MGliem commented on apps/backend/api/src/typeorm/User.ts
> +    default: '',
default idem

2023-01-03 16:32 UTC, MGliem commented on apps/backend/api/src/typeorm/User.ts
> +    default: '',
idem

2023-01-03 16:32 UTC, MGliem commented on apps/backend/api/src/typeorm/index.ts
> +
du coup non si on met les entités dans un tableau

2023-01-04 09:08 UTC, MGliem requested changes

2023-01-04 09:08 UTC, MGliem commented on apps/frontend/web/src/pages/SignUp.tsx
> +            <FormControl>
peut etre dans le meme FormControl

2023-01-04 09:08 UTC, MGliem commented on apps/frontend/web/src/pages/SignUp.tsx
> +            <FormControl>
peut etre dans le meme FormControl

2023-01-04 09:08 UTC, MGliem commented on apps/frontend/web/src/pages/SignUp.tsx
> +              <Button
Manque le shadow

2023-01-04 09:10 UTC, MGliem requested changes

2023-01-04 09:10 UTC, MGliem commented on apps/frontend/web/src/pages/SignUp.tsx
> +                <Input
Padding dans tous les inputs

2023-01-04 12:50 UTC, DangirasH commented on apps/backend/api/src/app.module.ts
> +        entities: entities,
''entities" est deja une tableau qui se retrouve src/typeorm/index.ts 
on retrouve tout les entities ici qui nous reduit le code dans app.module

2023-01-04 12:52 UTC, DangirasH commented on apps/backend/api/src/auth/auth.module.ts
> +      signOptions: { expiresIn: '60s' },
Eh oui ce bien ca, pour du testing j'avais mits 60s et j'ai oublier de augmenter, tu veut que je le change en combien?
Je vais mettre 4h pour l'instant

2023-01-04 14:00 UTC, DangirasH commented on apps/frontend/web/src/pages/SignUp.tsx
> +            fontFamily={'Lexend Deca'}
quelle partie?

2023-01-04 14:02 UTC, DangirasH commented on apps/frontend/web/src/pages/Login.tsx
> +          console.log('SUCCESS');
je laisse ca jusqu la fin de la PR

2023-01-04 14:02 UTC, DangirasH commented on apps/frontend/web/src/pages/Login.tsx
> +          console.log('ERROR');
idem

2023-01-04 14:05 UTC, DangirasH commented on apps/frontend/web/src/pages/Login.tsx
> +    <Stack minH={'100vh'} direction={{ base: 'column', md: 'row' }}>
je mets 95vh visiblment ce ca qui repond au 80px mais faudra reverifier si ce bon quand la navbar sera presente

2023-01-05 08:36 UTC, DangirasH commented on apps/backend/api/src/app.module.ts
> +import entities from './typeorm';
vue que j'ai mits le tableau dans ce ficher de typeorm ce bon alors pour le moment tant que /libs ne fonctionne pas

2023-01-10 11:38 UTC, Ysedda requested changes
Back: 
    - Pour les messages de validation serveur, il faudra les préciser un par un ou bien return un statut particulier pour traiter l'affichage afin de ne pas divulguer le nom des colonnes dans la DBB
    - Il manque les asserts de longeur dans l'entité user pour les colonnes de BDD

Front:
    - Il manque l'affichage des messages d'erreur serveur
    - Border dans les inputs sur certains champs et pas d'autres
    - Font-weight dans les champs à mettre en light + éventuellement réduire la taille de la police
    - Police des boutons un poil plus grosse
    - (responsive) Police trop grosse
    - (responsive) Trop d'espacement entre le Heading et le formulaire
    - (responsive) Manque d'espacement en bas de page 
![Screenshot_20230110_123630](https://user-images.githubusercontent.com/86974668/211541985-fd3a2a4f-13fb-42bf-bde0-4f1e3ed4f2be.png)

    - Page /login:
         - Titre à droite pas assez visible + manque de padding 
         - Image un peu trop petite, une taille en vw (j'ai mis 37 ou 38 sur les miennes) ferait l'affaire (plus simple en responsive)

    - Page /register:
         - Partie de gauche pas assez visible
         - Manque de padding dans le bouton "create an account" + font size

2023-01-10 11:38 UTC, Ysedda commented on apps/backend/api/src/users/users.controller.ts
> +  Inject,
'Inject' assigned but never used

2023-01-10 11:38 UTC, Ysedda commented on apps/backend/api/src/users/users.controller.ts
> +import { CreateUserDto } from './dto/create-user.dto';
'CreateUserDto' is assigned but never used

2023-01-10 11:38 UTC, Ysedda commented on apps/backend/api/src/users/users.service.ts
> +    console.log(password);
console.log

2023-01-10 11:38 UTC, Ysedda commented on apps/backend/api/src/users/users.service.ts
> +  ];
Mieux vaut éviter et mettre un/des user/s dans la lib inserts

2023-01-10 11:38 UTC, Ysedda commented on apps/frontend/web/src/pages/Login.tsx
> +  calc,
'calc' is assigned a value but never used

2023-01-10 11:38 UTC, Ysedda commented on apps/frontend/web/src/pages/Login.tsx
> +  const onSubmit = (event: any) => {
:any 😱

2023-01-10 11:38 UTC, Ysedda commented on apps/frontend/web/src/pages/Login.tsx
> +    console.log('handle');
console.log

2023-01-10 11:38 UTC, Ysedda commented on apps/frontend/web/src/pages/Login.tsx
> +          window.location.href = '/';
pas de href

2023-01-10 11:38 UTC, Ysedda commented on apps/frontend/web/src/pages/Login.tsx
> +              </Text>
Pas besoin de préciser le message d'erreur ici, tu peux le mettre dans {...register('email', (cf. ligne 63/64) et la lib le fera auto

2023-01-10 11:38 UTC, Ysedda commented on apps/frontend/web/src/pages/Login.tsx
> +            )}
Pareil

2023-01-10 11:38 UTC, Ysedda commented on apps/frontend/web/src/pages/Login.tsx
> +      </Box>
Un component Image suffit (cf. ma pr)

2023-01-10 11:38 UTC, Ysedda commented on apps/frontend/web/src/pages/Login.tsx
> +          Sign Up and discover the joys of sining during your trip
```suggestion
          Sign up and discover the joys of singing during your trip
```

2023-01-10 11:38 UTC, Ysedda commented on apps/frontend/web/src/pages/Login.tsx
> +        <Link href="/signup">
href 😱

2023-01-10 11:38 UTC, Ysedda commented on apps/frontend/web/src/pages/Login.tsx
> +              onChange={(event) => setPassword(event.target.value)}
pas besoin, la lib gère ça auto

2023-01-10 11:38 UTC, Ysedda commented on apps/frontend/web/src/pages/Login.tsx
> +              onChange={(event) => setEmail(event.target.value)}
pas besoin, la lib gère ça auto

2023-01-10 11:38 UTC, Ysedda commented on apps/frontend/web/src/pages/Login.tsx
> +                boxShadow={'0 4px 4px rgba(0, 0, 0, 0.25)'}
Max a créé un style pour les boutons dans la config de Chakra

2023-01-10 11:38 UTC, Ysedda commented on apps/frontend/web/src/pages/Login.tsx
> +          >
Style de bouton dans le thème Chakra

2023-01-17 13:39 UTC, MGliem requested changes
- Enlever le mini sur le prénom/nom
- Indiquer qu'il faut mini 8 characteres pour le mot de passe (mettre une erreur si ce n'est pas le cas)
( Les 2 remarques sont mise aux bonnes lignes ci dessous )

2023-01-17 13:39 UTC, MGliem commented on apps/backend/api/src/entities/User.ts
> +    nullable: true,
Enlever le nullable: true. La date Now() se met auto avec @CreateDateColumn

2023-01-17 13:39 UTC, MGliem commented on apps/backend/api/src/entities/User.ts
> +  deletedAt: Date;
@DeleteDateColumn
https://typeorm.io/decorator-reference#deletedatecolumn

2023-01-17 13:39 UTC, MGliem commented on apps/backend/api/src/users/dto/create-user.dto.ts
> +  @MinLength(3)
a modifier ici du coup la min length du nom (cf nom asiatiques)

2023-01-17 13:39 UTC, MGliem commented on apps/backend/api/src/users/dto/create-user.dto.ts
> +  @MinLength(10)
8 c'est déjà suffisant: penser à l'indiquer dans le front que c'est 8 mini

2023-01-17 13:39 UTC, MGliem commented on apps/backend/api/src/users/dto/create-user.dto.ts
> +  confirmPassword: string;
je pense que la verif du "confirm password" devrait se passer uniquement côté front. On en a pas besoin dans le back et c'est juste un quality of life pour le user qui lui permet de savoir qu'il n'a pas miss-key son clavier lors de la saisie de sont MDP.

2023-01-17 13:39 UTC, MGliem commented on apps/backend/api/src/users/users.service.ts
> +      );
a faire uniquement dans le front et ne même pas envoyer le confirm password au back

2023-01-17 13:39 UTC, MGliem commented on apps/frontend/web/src/pages/SignUp.tsx
> +import React, { useState } from 'react';
```suggestion
import { useState } from 'react';
```

2023-01-17 13:39 UTC, MGliem commented on apps/frontend/web/src/pages/SignUp.tsx
> +        confirmPassword,
Ne pas envoyer le confirmpassword au back

2023-01-17 13:39 UTC, MGliem commented on apps/frontend/web/src/pages/SignUp.tsx
> +              })}
Pour le check de confirm password avec react hook form https://stackoverflow.com/questions/70480928/how-to-validate-password-and-confirm-password-in-react-hook-form-is-there-any-v

2023-01-17 13:39 UTC, MGliem commented on apps/frontend/web/src/pages/SignUp.tsx
> +              })}
Rajouter la min lenght de 8:
minLength: {
            value: 8,
            message: "Password must have at least 8 characters"
          }

2023-01-18 13:40 UTC, Ysedda requested changes
- Quand j'essaie de me connecter sans avoir créé de compte, erreur 500 dans la console et ERROR [ExceptionsHandler] Cannot read properties of null (reading 'password') côté Nest sans affichage dans le front (ça fait référence à mon commentaire de review sur la gestion des erreurs de la page login).

Front: 

- Global: Boutons plus gros (cf. les boutons components de la partie create-trip)
- Login:  partie de gauche pas centrée verticalement
- Signup: police en fontWeight={'light'} sur les placeholders et  les inputs
- Signup (responsive): police trop grosse, inputs pas centrés et bande blanche en bas de page en vue tablette 
![Screenshot_20230118_143711](https://user-images.githubusercontent.com/86974668/213185742-4ec492ff-9294-4f59-86ad-528d628db17f.png)
- Login (responsive) : 
![Screenshot_20230118_142825](https://user-images.githubusercontent.com/86974668/213184774-46dcd65f-dbdb-4d4d-943e-77c4e271a3e7.png)
  Trop d'espace au dessus de "log in to your account" et pas assez sous le bouton "login

2023-01-18 13:40 UTC, Ysedda commented on apps/frontend/web/src/pages/SignUp.tsx
> +              Email address
```suggestion
              {'Email address'}
```

2023-01-18 13:40 UTC, Ysedda commented on apps/frontend/web/src/pages/SignUp.tsx
> +              Password
```suggestion
              {'Password'}
```

2023-01-18 13:40 UTC, Ysedda commented on apps/frontend/web/src/pages/SignUp.tsx
> +              Confirm Password
```suggestion
              {'Confirm Password'}
```

2023-01-18 13:40 UTC, Ysedda commented on apps/frontend/web/src/pages/SignUp.tsx
> +              Create an account
```suggestion
              {'Create an account'}
```

2023-01-18 13:40 UTC, Ysedda commented on apps/frontend/web/src/pages/SignUp.tsx
> +        }
ça fait un message d'erreur très générique pour tous les autres types et codes d'erreur, il faudrait mieux récupérer les messages de validation du nest et les set dans un state ici

2023-01-18 13:40 UTC, Ysedda commented on apps/frontend/web/src/pages/SignUp.tsx
> +        }
et les validations du password ne sont plus nécessaires vu qu'elles se font dans le front

2023-01-18 14:29 UTC, DangirasH commented on apps/frontend/web/src/pages/Login.tsx
> +              placeholder={'**********'}
damn t'as l'oeil

2023-01-22 16:23 UTC, MGliem approved these changes

2023-01-24 08:51 UTC, YDrogen requested changes

2023-01-24 08:51 UTC, YDrogen commented on apps/backend/api/src/auth/auth.controller.ts
> +    return { message: 'connection succesful', status: 'SUCCESS' };
```suggestion
    return { message: 'connection successful', status: 'SUCCESS' };
```

2023-01-24 08:51 UTC, YDrogen commented on apps/backend/api/src/auth/auth.module.ts
> +import { UsersService } from 'src/users/users.service';
import pas bon -> il faut du relatif

2023-01-24 08:51 UTC, YDrogen commented on apps/backend/api/src/auth/auth.service.ts
> +import { comparePasswords } from 'src/utils/bcrypt';
import

2023-01-24 08:51 UTC, YDrogen commented on apps/backend/api/src/auth/auth.service.ts
> +import { User } from 'src/entities';
import

2023-01-24 08:51 UTC, YDrogen commented on apps/backend/api/src/auth/auth.service.ts
> +  async validateUser(email: string, password: string): Promise<any> {
`any` ?

2023-01-24 08:51 UTC, YDrogen commented on apps/backend/api/src/auth/local.strategy.ts
> +  async validate(email: string, password: string): Promise<any> {
`any` ?

2023-01-24 08:51 UTC, YDrogen commented on apps/backend/api/src/entities/user.entity.ts
> +  @Column({ type: 'text', nullable: true })
Pas de type `text`

2023-01-24 08:51 UTC, YDrogen commented on apps/backend/api/src/main.ts
> +  const COOKIE_SECRET = configService.get('COOKIE_SECRET');
Ça pourrait être remonté de 2 lignes pour une meilleure lisibilité :)

2023-01-24 08:51 UTC, YDrogen commented on apps/backend/api/src/users/dto/create-user.dto.ts
> +  @MinLength(10)
resolved mais pas prit en compte ?

2023-01-24 08:51 UTC, YDrogen commented on apps/backend/api/src/users/dto/create-user.dto.ts
> +  birthdays: Date;
resolved mais pas prit en compte ?

2023-01-24 08:51 UTC, YDrogen commented on apps/backend/api/src/users/types/index.ts
> +}
C'est pas un peu too much un serializer ?

2023-01-24 08:51 UTC, YDrogen commented on apps/backend/api/src/users/users.controller.ts
> +import { SerializedUser } from './types/index';
Un serializer dans le dossier `types` ?

2023-01-24 08:51 UTC, YDrogen commented on apps/backend/api/src/users/users.service.ts
> +import { encodePassword } from 'src/utils/bcrypt';
import

2023-01-24 08:51 UTC, YDrogen commented on apps/backend/api/src/users/users.service.ts
> +  }
???

2023-01-24 08:51 UTC, YDrogen commented on apps/frontend/web/src/pages/Login.tsx
> +      }
Une erreur 500 signifie que le serveur a planté;
`Account not found` ça serait plus une erreur 404 du coup
En revanche, il ne faut pas faire la différence avec la première erreur
Là, si on se trompe de mail, on a l'erreur `Account not found` donc si on a la bon mail mais le mauvais mot de passe, on aura `Incorrect email or password` mais on sait déjà que le mail existe puisqu'on n'a pas `Account not found`

2023-01-24 08:51 UTC, YDrogen commented on apps/frontend/web/src/pages/Login.tsx
> +                required: 'A password with atleast 8 characters is required',
`required` = pas vide
-> Message pas bon
Il manque `minLength` avec la même valeur que sur le back (10) ou mettre 8 dans le back

2023-01-25 10:00 UTC, Ysedda commented on apps/frontend/web/src/pages/SignUp.tsx
>            Create an account
```suggestion
          {'Create an account'}
```

2023-01-25 10:02 UTC, Ysedda commented on apps/frontend/web/src/pages/SignUp.tsx
>            <Grid templateColumns={'1fr 1fr'} gap={5}>
Pourquoi une grid pour 2 champs ?

2023-01-25 13:34 UTC, Ysedda requested changes

2023-01-25 13:34 UTC, Ysedda commented on apps/backend/api/src/auth/auth.service.ts
> +import { ValidateUser } from '../../../../../libs/typings/src/types/ValidateUser';
```suggestion
import { ValidateUser } from '@libs/typings';
```

2023-01-25 13:34 UTC, Ysedda commented on apps/backend/api/src/auth/local.strategy.ts
> +import { ValidateUser } from '../../../../../libs/typings/src/types/ValidateUser';
```suggestion
import { ValidateUser } from '@libs/typings';
```

2023-01-25 13:34 UTC, Ysedda commented on apps/frontend/web/src/pages/Login.tsx
> +  const onSubmit = async (data: Partial<object>) => {
```suggestion
  const onSubmit = async (data: Partial<User>) => {
```

2023-01-25 13:34 UTC, Ysedda commented on libs/typings/src/types/ValidateUser.ts
> +};
Plus besoin

2023-01-25 13:34 UTC, Ysedda commented on libs/typings/src/interfaces/index.ts
> +}
plus besoin

2023-01-25 13:34 UTC, Ysedda commented on libs/typings/src/types/ValidateUser.ts
> +) => Promise<Partial<User>>;
```suggestion
export type ValidateUser = {
  id: number,
  email: string,
  password: string
};
```

2023-01-25 14:06 UTC, Ysedda approved these changes

2023-01-25 15:24 UTC, YDrogen requested changes

2023-01-25 15:24 UTC, YDrogen commented on apps/backend/api/src/users/users.controller.ts
> +  @Post('create')
Pourquoi `create` ?

2023-01-25 15:24 UTC, YDrogen commented on apps/frontend/web/src/pages/Login.tsx
> +        <Box as={'form'} onSubmit={handleSubmit(onSubmit)}>
Il manque quelque chose dans le `onSubmit` là

2023-01-25 15:24 UTC, YDrogen commented on apps/frontend/web/src/pages/SignUp.tsx
> +        <Box as={'form'} onSubmit={handleSubmit(onSubmit)}>
Idem

2023-01-25 15:24 UTC, YDrogen commented on apps/backend/api/src/users/users.controller.ts
> +  @UsePipes(ValidationPipe)
Pourquoi ?

2023-01-26 11:18 UTC, Ysedda requested changes

2023-01-26 11:18 UTC, Ysedda commented on apps/backend/api/src/auth/auth.service.ts
> +import { User as UserEntity } from '../entities';
```suggestion
import { User } from '../entities';
```

2023-01-26 11:18 UTC, Ysedda commented on apps/backend/api/src/auth/auth.service.ts
> +  async login(user: UserEntity) {
```suggestion
  async login(user: User) {
```

2023-01-26 11:18 UTC, Ysedda commented on apps/backend/api/src/users/users.service.ts
>  import { User as UserEntity } from '../entities';
```suggestion
import { User } from '../entities';
```

2023-01-26 11:18 UTC, Ysedda commented on apps/backend/api/src/users/users.service.ts
>      private readonly userRepository: Repository<UserEntity>,
```suggestion
    private readonly userRepository: Repository<User>,
```

2023-01-26 11:18 UTC, Ysedda commented on apps/backend/api/src/users/users.service.ts
> +  async findUserByEmail(email: string): Promise<UserEntity | undefined> {
```suggestion
  async findUserByEmail(email: string): Promise<User | undefined> {
```

2023-01-26 13:22 UTC, Ysedda submitted a review, later dismissed

2023-01-26 13:51 UTC, YDrogen requested changes

2023-01-26 13:51 UTC, YDrogen commented on apps/backend/api/src/auth/auth.service.ts
> +        throw new ConflictException('Email already exists');
```suggestion
        throw new ConflictException('Email already used');
```

2023-01-26 15:18 UTC, Ysedda approved these changes

2023-01-26 16:06 UTC, merged