Feature/trip search
WildCodeSchool/2022-09-Orleans-CDA-Projet-KaraoCar pull request #28
Opened 2023-01-03 16:28 UTC by epereira

2023-01-04 10:05 UTC, MGliem requested changes
Il manque pas mal de choses même si on met de côté tout le back.
- Manque le SVG
- le titre de la page n'est pas placé où il faut ni à la bonne taille.
- la searchbar doit être plus épaisse
- le bouton search à trop d'espace horizontale
- c'est bizarre au niveau des border bleu et le shadow entre chaque input de la searchbar

2023-01-04 10:49 UTC, epereira commented on apps/frontend/web/src/pages/Search.tsx
> +import SearchBar from "../theme/components/searchBar";
Ok bien vu, j'ai pas que ce dossier components étaient  dans le dossier thème, le nom n'est pas le bon à cause de la casse.

2023-01-05 19:45 UTC, MGliem requested changes
Il manque le responsive.
L'image est trop à droite et trop petite
La taille du titre de la page est trop petite.
Les coins à gauche du bouton search ne doivent pas être arrondies.
Il y a toujours ca qui fait bizarre: 
![image](https://user-images.githubusercontent.com/100389157/210866660-00f63a8f-57fa-4f08-9cfb-4c5ef2134d6d.png)
Le champ music est beaucoup trop long.
La barre de manière générale me parait pas assez haute.

2023-01-10 16:08 UTC, epereira commented
> Il manque le responsive. L'image est trop à droite et trop petite La taille du titre de la page est trop petite. Les coins à gauche du bouton search ne doivent pas être arrondies. Il y a toujours ca qui fait bizarre: ![image](https://user-images.githubusercontent.com/100389157/210866660-00f63a8f-57fa-4f08-9cfb-4c5ef2134d6d.png) Le champ music est beaucoup trop long. La barre de manière générale me parait pas assez haute.

Corrigé

2023-01-10 16:08 UTC, closed without merging