Feature Chat
WildCodeSchool/2022-09-Orleans-CDA-Projet-KaraoCar pull request #35
Opened 2023-01-08 19:34 UTC by MGliem

Full responsive

2023-01-09 16:01 UTC, Ysedda commented on libs/typings/src/interfaces/Conversation.ts
> +}
À supprimer et importer depuis index.ts dans le back (c.f ma pr)

2023-01-09 16:01 UTC, Ysedda commented on libs/typings/src/interfaces/Message.ts
> +}
À supprimer et importer depuis index.ts dans le back (c.f ma pr)

2023-01-09 16:01 UTC, Ysedda commented on libs/typings/src/interfaces/index.ts
> +export * from './Message';
À supprimer

2023-01-09 16:09 UTC, Ysedda commented on apps/frontend/web/src/components/chat/ChatWithUser.tsx
> +                        message.receiver_id === user.id ? '#394E61' : '#E4F2FF'
Faudrait mettre les couleurs réutilisées dans le thème chakra (le #394E51 c'est slateblue je le reconnais)

2023-01-09 16:10 UTC, Ysedda commented on apps/frontend/web/src/components/chat/ChatWithUser.tsx
> +                      message.receiver_id === user.id ? '#394E61' : '#E4F2FF'
thème

2023-01-09 16:10 UTC, Ysedda commented on apps/frontend/web/src/components/chat/ChatWithUser.tsx
> +                        message.receiver_id === user.id ? '#FFFFFF' : '#000000'
thème + pas de blanc blanc ni de noir noir

2023-01-09 16:12 UTC, Ysedda commented on apps/frontend/web/src/pages/Chat.tsx
> +import { Conversation, Message } from '@libs/typings';
à import depuis @apps/backend-api après les modifs

2023-01-10 13:22 UTC, Ysedda requested changes
Front: 
- Sidebar à cacher quand il n'y a pas de conversations

2023-01-10 14:04 UTC, Ysedda submitted a review, later dismissed

2023-01-16 16:26 UTC, YDrogen requested changes

2023-01-17 09:07 UTC, MGliem commented on apps/backend/api/src/messages/messages.controller.ts
> +    @Param('senderId') senderId: string,
j'ai fait autrement, je passe par le message id. Ca évite de faire un querybuilder en +

2023-01-17 09:21 UTC, MGliem commented on apps/frontend/web/src/components/chat/ChatWithUser.tsx
> +  user: { id: number };
En effet, peut être à revoir dés qu'on a la logique d'authentification d'implementé

2023-01-17 14:26 UTC, Ysedda approved these changes

2023-01-18 08:49 UTC, YDrogen requested changes

2023-01-18 08:49 UTC, YDrogen commented on apps/frontend/web/src/components/chat/Sidebar.tsx
> +            {conversations.length > 0 && 'Conversations'}
Attention avec les `&&`
`[].length > 0 && 'Conversations'` -> `false`
`[''].length > 0 && 'Conversations'` -> `Conversations`

2023-01-18 15:33 UTC, paul-chatelain-fernandes commented on apps/frontend/web/src/components/chat/Sidebar.tsx
> +      markAsRead();
Utilise les IIFE, ça te simplifera la vie conseil de pro

2023-01-19 08:20 UTC, Ysedda submitted a review, later dismissed

2023-01-19 14:26 UTC, epereira commented on apps/frontend/web/src/pages/Chat.tsx
> +          `/api/messages/mark-as-read?user=${user.id}&contact=${chattingWithUserId}`,
Passer les id dans l'url du fetch ne risque pas de poser des failles de sécurité ? Ne serait pas mieux d'attendre et finaliser une fois l'authentification et que le token soit ajouté ?

2023-01-19 14:32 UTC, epereira commented on apps/frontend/web/src/pages/Chat.tsx
> +    const months = [
Pourquoi faire ?
Ca ne marche pas ça : date.toLocaleDateString("en-US", { month: 'short' }) ?

2023-01-19 14:35 UTC, MGliem commented on apps/frontend/web/src/pages/Chat.tsx
> +          `/api/messages/mark-as-read?user=${user.id}&contact=${chattingWithUserId}`,
Effectivement, ca ce fera une fois le login mis en place comme marqué en commentaire dans le nest. En attendant nous faisons comme ca pour avoir quelque chose qui fonctionne

2023-01-19 14:36 UTC, MGliem commented on apps/frontend/web/src/pages/Chat.tsx
> +    let url = `/api/messages/${user.id}/${chattingWithUserId}`;
même réponse qu'au dessus

2023-01-19 14:41 UTC, MGliem commented on apps/frontend/web/src/pages/Chat.tsx
> +    const months = [
à oui, ca fonctionne, bien joué

2023-01-19 15:27 UTC, Ysedda submitted a review, later dismissed

2023-01-19 16:33 UTC, YDrogen requested changes

2023-01-19 16:33 UTC, YDrogen commented on apps/frontend/web/src/components/chat/ChatWithUser.tsx
> +                    message.receiver_id === user.id ? 'row' : 'row-reverse'
```javascript
message.receiver_id === user.id
```
répété trop de fois, ça pourrait être une `const` hors du `return`

2023-01-19 20:15 UTC, MGliem commented on apps/backend/api/src/messages/messages.controller.ts
> +    if (+createMessageDto.sender === this.userId) {
Par ce que dans le DTO je suis obligé de le typer en User

2023-01-19 20:29 UTC, MGliem commented on apps/frontend/web/src/components/chat/ChatWithUser.tsx
> +                    message.receiver_id === user.id ? 'row' : 'row-reverse'
On peut faire ca ? Ici je suis dans un messageS.map et cette condition change en fonction de chaque message

2023-01-19 20:30 UTC, MGliem commented on apps/frontend/web/src/components/chat/Sidebar.tsx
> +    if (conversation.sender_id === user.id) {
Idem, cette fonction est appelé dans un conversationS.map.

2023-01-21 12:28 UTC, YDrogen requested changes

2023-01-21 12:28 UTC, YDrogen commented on apps/frontend/web/src/pages/Chat.tsx
> +    noScroll: boolean = true
Les paramètres obligatoires doivent être en premier

2023-01-21 12:28 UTC, YDrogen commented on apps/frontend/web/src/pages/Chat.tsx
> +      getMessages(null, true, false);
ça permet d'éviter de devoir mettre `null` à chaque fois pour rien si on veut modifier les params d'après

2023-01-23 08:13 UTC, Ysedda approved these changes

2023-01-25 00:31 UTC, YDrogen approved these changes

2023-01-25 00:31 UTC, merged