Feature/user profile
WildCodeSchool/2022-09-Orleans-CDA-Projet-KaraoCar pull request #42
Opened 2023-01-17 15:08 UTC by Ysedda

2023-01-25 16:35 UTC, YDrogen requested changes

2023-01-26 08:35 UTC, Ysedda commented on apps/backend/api/src/users/users.controller.ts
> +import path = require('path');
🙄

2023-01-26 08:36 UTC, Ysedda commented on apps/frontend/web/src/pages/UserProfile.tsx
> +      <Box as="form" onSubmit={handleSubmit(onSubmit)}>
https://react-hook-form.com/api/useform/handlesubmit

marche pas avec une callback

2023-01-26 21:00 UTC, MGliem approved these changes
Le fichier UserProfile est énoOoooOOOOOooorme 600+lignes.
Néanmoins, en regardant, difficile de le découper je pense. 
Peut être componenter  :
 - les musical choices avec son fetch
 - la partie photo
 - le reste des GridItem

2023-01-27 10:23 UTC, YDrogen requested changes

2023-01-28 23:28 UTC, MGliem approved these changes

2023-01-29 00:30 UTC, YDrogen approved these changes

2023-01-29 00:30 UTC, merged