Feature/trip next
WildCodeSchool/2022-09-Orleans-CDA-Projet-KaraoCar pull request #52
Opened 2023-01-26 15:10 UTC by epereira

2023-01-26 21:41 UTC, MGliem requested changes
Tu as toute ta PR précédente dans celle ci sans qu'il n'y ai eu aucun changement.
Tu vas être embêté par ce que tu vas devoir modifier le code dans les 2 branches pour tous les changements qui vont être demandé.

De plus, tu te retrouve ici avec des fichiers/changements qui n'ont rien à faire dans cette PR (la page search ou la searchbar par exemple), ce qui rend la review plus laborieuse.

Comme je l'ai mis en commentaire plus bas:
Tu ne devrais pas créer 2 pages Next et Past mais plutôt une page "MyTrips" et un component "MyTripsDetails". Ce component afficherai dans MyTrips en fonction des props que tu envoie les past ou upcomming trips ("upcomming" et plus correcte que "next")

2023-01-26 21:41 UTC, MGliem commented on apps/backend/api/src/trips/dto/query-search-trip.dto.ts
> +  musicalChoice: number;
même remarque que dans la PR précédente

2023-01-26 21:41 UTC, MGliem commented on apps/backend/api/src/trips/dto/query-search-trip.dto.ts
> +  dateDeparture: Date;
même remarque que dans la PR précédente

2023-01-26 21:41 UTC, MGliem commented on apps/backend/api/src/trips/dto/query-search-trip.dto.ts
> +  nbPassengers: number;
même remarque que dans la PR précédente

2023-01-26 21:41 UTC, MGliem commented on apps/backend/api/src/trips/trips.service.ts
> +  }
même remarque que dans la PR précédente

2023-01-26 21:41 UTC, MGliem commented on apps/backend/api/src/trips/trips.service.ts
> +    });
C'est dans le controller que tu passes le user id ici en paramètre

2023-01-26 21:41 UTC, MGliem commented on apps/frontend/web/src/components/navbar/Navbar.tsx
> +    myTrips: '/next-trips',
next-trips ?

2023-01-26 21:41 UTC, MGliem commented on apps/frontend/web/src/components/searchbar/SearchBar.tsx
> +        : 1,
même remarque que dans la PR précédente

2023-01-26 21:41 UTC, MGliem commented on apps/frontend/web/src/components/searchbar/SearchBar.tsx
> +  const [criteria, setCriteria] = useState<SearchCriteria>({});
même remarque que dans la PR précédente

2023-01-26 21:41 UTC, MGliem commented on apps/frontend/web/src/components/searchbar/SearchBar.tsx
> +  Stack,
stack unused

2023-01-26 21:41 UTC, MGliem commented on apps/frontend/web/src/components/searchbar/SearchBar.tsx
> +import { MouseEvent, MouseEventHandler, useEffect, useState } from 'react';
même remarque que dans la PR précédente

2023-01-26 21:41 UTC, MGliem commented on apps/frontend/web/src/components/searchbar/SearchBar.tsx
> +      .map((k) => encodeURIComponent(k) + '=' + encodeURIComponent(params[k]))
même remarque que dans la PR précédente

2023-01-26 21:41 UTC, MGliem commented on apps/frontend/web/src/components/triplist/TripList.tsx
> +import { title } from 'process';
unused

2023-01-26 21:41 UTC, MGliem commented on apps/frontend/web/src/components/triplist/TripList.tsx
> +  const musicList = '';
unused

2023-01-26 21:41 UTC, MGliem commented on apps/frontend/web/src/components/triplist/TripList.tsx
> +                      src={'../../../public/images/seat.svg'}
même remarque que dans la PR précédente

2023-01-26 21:41 UTC, MGliem commented on apps/frontend/web/src/components/triplist/TripList.tsx
> +                    src="../../../public/images/profile-placeholder.png"
même remarque que dans la PR précédente

2023-01-26 21:41 UTC, MGliem commented on apps/frontend/web/src/components/triplist/TripList.tsx
> +                  ***3 avenue du champ de Mars, 45 000 ORLEANS
On a ces infos dans la BDD. Pourquoi les mettre en dur ?

2023-01-26 21:41 UTC, MGliem commented on apps/frontend/web/src/components/triplist/TripList.tsx
> +                  ***20 place de la République, 41 000 BLOIS
On a ces infos dans la BDD. Pourquoi les mettre en dur ?

2023-01-26 21:41 UTC, MGliem commented on apps/frontend/web/src/components/triplist/TripList.tsx
> +                                '../../../public/images/undraw_by_my_car_gicy.svg'
mauvais lien

2023-01-26 21:41 UTC, MGliem commented on apps/frontend/web/src/components/triplist/TripList.tsx
> +                                src="../../../public/images/profile-placeholder.png"
mauvais src

2023-01-26 21:41 UTC, MGliem commented on apps/frontend/web/src/components/triplist/TripList.tsx
> +                              }
mauvais src

2023-01-26 21:41 UTC, MGliem commented on apps/frontend/web/src/components/triplist/TripList.tsx
> +                                ***3 avenue du champ de Mars, 45 000 ORLEANS
on a l'info en BDD

2023-01-26 21:41 UTC, MGliem commented on apps/frontend/web/src/components/triplist/TripList.tsx
> +                                      src="../../../public/images/profile-placeholder.png"
mauvais src

2023-01-26 21:41 UTC, MGliem commented on apps/frontend/web/src/components/triplist/TripList.tsx
> +                                ***20 place de la République, 41 000 BLOIS
info en BDD

2023-01-26 21:41 UTC, MGliem commented on apps/frontend/web/src/interfaces/SearchCriteriaInterface.ts
> +}
Même remarque que PR précédente

2023-01-26 21:41 UTC, MGliem commented on apps/frontend/web/src/pages/TripsNext.tsx
> +const TripsNext = () => {
Plutot MyTrips

2023-01-26 21:41 UTC, MGliem commented on apps/frontend/web/src/pages/TripsNext.tsx
> +              <Img src="../../public/images/undraw_order_ride.svg" w={'50%'} />
mauvais src

2023-01-26 21:41 UTC, MGliem commented on apps/frontend/web/src/pages/TripsNext.tsx
> +          <Link to="/past-trips">
Je ne voyais pas ca comme ca. Plutot une page 'my trips' dans laquelle tu as dedans 1 component MyTripsDetails avec des props pour soit afficher les upcomming ou les pasts trips

2023-01-26 21:41 UTC, MGliem commented on apps/frontend/web/src/pages/TripsNext.tsx
> +              you haven't upcoming trips
You have no upcoming trips

2023-01-26 21:41 UTC, MGliem commented on apps/frontend/web/src/pages/TripsPast.tsx
> +const TripsNext = () => {
TripsNext aussi ???
On a 2 fois presque le même code dans 2 fichiers différents

2023-01-26 21:41 UTC, MGliem commented on apps/frontend/web/src/pages/TripsPast.tsx
> +              <Img src="../../public/images/undraw_order_ride.svg" w={'50%'} />
src

2023-01-26 21:41 UTC, MGliem commented on package.json
> +    "@nestjs/mapped-types": "*",
même remarque que PR précédente

2023-02-02 15:50 UTC, epereira commented on apps/frontend/web/src/components/navbar/Navbar.tsx
> +    myTrips: '/next-trips',
changed to upcoming-trips

2023-02-02 15:51 UTC, epereira commented on apps/frontend/web/src/components/searchbar/SearchBar.tsx
> +  Stack,
removed

2023-02-02 16:00 UTC, epereira commented on apps/frontend/web/src/pages/TripsNext.tsx
> +              you haven't upcoming trips
you don't have an upcoming trip

2023-02-02 16:01 UTC, epereira commented on apps/frontend/web/src/pages/TripsPast.tsx
> +const TripsNext = () => {
copier-coller

2023-02-02 16:02 UTC, epereira commented on apps/frontend/web/src/pages/TripsPast.tsx
> +const TripsNext = () => {
refactorisation prévue

2023-02-07 20:17 UTC, closed without merging