Feature user logic for chat
WildCodeSchool/2022-09-Orleans-CDA-Projet-KaraoCar pull request #66
Opened 2023-01-30 19:07 UTC by MGliem

2023-01-30 19:33 UTC, Ysedda approved these changes

2023-01-31 08:11 UTC, YDrogen requested changes

2023-01-31 08:11 UTC, YDrogen commented on apps/frontend/web/src/components/chat/ChatWithUser.tsx
> +  user: Pick<User, 'id'> | undefined;
```suggestion
  user?: Pick<User, 'id'>;
```

2023-01-31 08:11 UTC, YDrogen commented on apps/frontend/web/src/components/chat/Sidebar.tsx
> +  user: Pick<User, 'id'> | undefined;
idem

2023-01-31 08:55 UTC, Ysedda approved these changes

2023-01-31 09:13 UTC, YDrogen approved these changes

2023-01-31 09:13 UTC, merged