Feature/mobile trips
WildCodeSchool/2022-09-Orleans-CDA-Projet-KaraoCar pull request #71
Opened 2023-02-01 14:04 UTC by Ysedda

2023-02-01 20:27 UTC, MGliem requested changes

2023-02-01 20:27 UTC, MGliem commented on apps/frontend/mobile/App.tsx
> +        console.error(e);
j'sais pas si il y a mais si y a un petit toast ? (j'ai soif)

2023-02-02 09:00 UTC, MGliem approved these changes

2023-02-02 09:49 UTC, MGliem submitted a review, later dismissed

2023-02-02 10:32 UTC, MGliem approved these changes

2023-02-02 14:47 UTC, YDrogen requested changes

2023-02-02 14:47 UTC, YDrogen commented on apps/frontend/mobile/App.tsx
> +import { Avatar } from 'native-base';
native base est déjà importé

2023-02-02 14:47 UTC, YDrogen commented on apps/frontend/mobile/components/Trip.tsx
> +import { Avatar } from 'native-base';
idem

2023-02-02 14:47 UTC, YDrogen commented on apps/frontend/mobile/components/Trip.tsx
> +import { Avatar } from 'native-base';
idem

2023-02-02 14:47 UTC, YDrogen commented on apps/frontend/mobile/main.tsx
> +        await new Promise((resolve) => setTimeout(resolve, 2000));
pourquoi ?

2023-02-02 15:38 UTC, MGliem approved these changes

2023-02-02 15:48 UTC, YDrogen approved these changes

2023-02-02 15:49 UTC, merged