Feature show and rate past trips
WildCodeSchool/2022-09-Orleans-CDA-Projet-KaraoCar pull request #72
Opened 2023-02-01 20:16 UTC by MGliem

2023-02-01 21:49 UTC, Ysedda requested changes

2023-02-01 21:49 UTC, Ysedda commented on apps/backend/api/src/entities/rating.entity.ts
> +  trip: Trip;
la relation c'est pas vers TripSlice plutôt ?

2023-02-01 21:49 UTC, Ysedda commented on apps/backend/api/src/ratings/ratings.controller.ts
> +@Controller('ratings')
Autant mettre le UseGuards ici vu qu'on bloque toutes les routes

2023-02-01 21:49 UTC, Ysedda commented on apps/frontend/web/src/components/rating/RatingModal.tsx
> +          duration: 3000,
on est obligé de le mettre à chaque fois ?

2023-02-01 22:20 UTC, MGliem commented on apps/backend/api/src/ratings/ratings.controller.ts
> +@Controller('ratings')
Je ne sais, faudra être log pour faire une recherche de trajet ? (ca apparait la dessus aussi le rating)

2023-02-01 22:21 UTC, MGliem commented on apps/backend/api/src/entities/rating.entity.ts
> +  trip: Trip;
Comme sur le diagram, on fait une relation vers le trip, ca a plus de sens, on ne va pas rate chaque bout de voyage si on fait tout le voyage

2023-02-01 22:22 UTC, Ysedda commented on apps/backend/api/src/entities/rating.entity.ts
> +  trip: Trip;
le truc c'est que le gars rejoint pour un slice et pas forcément le trip complet

2023-02-01 22:23 UTC, MGliem commented on apps/frontend/web/src/components/rating/RatingModal.tsx
> +          duration: 3000,
Je pense que oui, je ne vois pas trop comment sinon vu que ca vient d'un hook

2023-02-02 08:56 UTC, Ysedda submitted a review, later dismissed

2023-02-02 15:24 UTC, YDrogen requested changes

2023-02-02 15:24 UTC, YDrogen commented on apps/frontend/web/src/pages/Home.tsx
> +      const req = await fetch('api/ratings/to-rate', {
il manque le `/`

2023-02-02 15:39 UTC, Ysedda submitted a review, later dismissed

2023-02-02 16:06 UTC, YDrogen approved these changes

2023-02-02 16:06 UTC, merged