Feature/user profile rating
WildCodeSchool/2022-09-Orleans-CDA-Projet-KaraoCar pull request #91
Opened 2023-02-07 14:08 UTC by Ysedda

2023-02-08 08:32 UTC, MGliem requested changes

2023-02-08 08:32 UTC, MGliem commented on apps/backend/api/src/users/users.service.ts
> +      .leftJoinAndSelect('user.musicalStyles', 'musicalStyle')
Vu que tu fais un select apres qui ecrase tous les précédents select, tu peux juste faire leftJoin ou innerJoin.

2023-02-08 16:11 UTC, MGliem approved these changes

2023-02-08 16:50 UTC, YDrogen requested changes

2023-02-08 16:50 UTC, YDrogen commented on apps/frontend/web/src/pages/UserProfile.tsx
> +                size={24}
hook `useBreakpoint` de Chakra

2023-02-09 09:33 UTC, MGliem submitted a review, later dismissed

2023-02-09 11:28 UTC, YDrogen requested changes

2023-02-09 11:28 UTC, YDrogen commented on apps/frontend/web/src/pages/UserProfile.tsx
> +          md: `"Firstname Firstname . Stars Stars "
Il n'y a pas **une** espace en trop ?

2023-02-09 12:29 UTC, Ysedda commented on apps/frontend/web/src/pages/UserProfile.tsx
> +          md: `"Firstname Firstname . Stars Stars "
🤷‍♂️

2023-02-09 13:20 UTC, MGliem approved these changes

2023-02-09 13:45 UTC, YDrogen approved these changes

2023-02-09 13:45 UTC, merged