Feature Trip Search
WildCodeSchool/2022-09-Orleans-CDA-Projet-KaraoCar pull request #93
Opened 2023-02-08 09:33 UTC by MGliem

2023-02-08 13:15 UTC, paul-chatelain-fernandes submitted a review, later dismissed
Très beau travail!

2023-02-08 13:38 UTC, Ysedda approved these changes

2023-02-08 16:06 UTC, YDrogen requested changes

2023-02-08 16:17 UTC, MGliem commented on apps/frontend/web/src/components/search-trip/TripSummary.tsx
> +                  <Text fontSize={'12px'}>{'52 votes'}</Text>
Oui (feature note ready)

2023-02-08 16:17 UTC, MGliem commented on apps/frontend/web/src/components/search-trip/TripSummary.tsx
> +                <Text fontSize={'18px'}>{'Mercedes Classe C Coupé'}</Text>
Oui

2023-02-09 08:19 UTC, Ysedda approved these changes

2023-02-09 08:48 UTC, YDrogen commented on apps/frontend/web/src/components/search-trip/TripSummary.tsx
> +        <Text>{trip.tripSlices && trip.tripSlices[0].price} €</Text>
**et pas d'espace avant le €**

2023-02-09 09:03 UTC, Ysedda approved these changes

2023-02-09 09:26 UTC, YDrogen approved these changes

2023-02-09 09:26 UTC, merged