Feature - testing user findOne and findOneBy
WildCodeSchool/2022-09-Orleans-CDA-Projet-KaraoCar pull request #95
Opened 2023-02-09 16:34 UTC by DangirasH

- run "npm run test users.service.ts" having opened the terminal in backend/api/src/users

2023-02-10 15:14 UTC, MGliem submitted a review, later dismissed

2023-02-13 08:39 UTC, YDrogen requested changes
A revoir complètement, il n'y a aucune logique de testée dedans
Le seul aspect testé est :
```typescript
const A = "bonjour";
const B = A;
B === A // ?
```
ce qui est un peu léger pour un service utilisant TypeORM

2023-02-13 08:39 UTC, YDrogen commented on apps/backend/api/src/users/users.service.ts
> +
inutile ?

2023-02-13 08:39 UTC, YDrogen commented on apps/backend/api/src/users/users.service.spec.ts
> +    };
Pourquoi mocker le repository ? (Ceci ne mock rien du tout)

2023-02-13 09:14 UTC, DangirasH commented on apps/backend/api/src/users/users.service.spec.ts
> +    };
Je mock le userRepository car nous voulons isoler le comportement de la classe UsersService et ne pas nous préoccuper du comportement de userRepository. En créant un objet userRepository, nous pouvons définir son comportement dans nos tests, puis affirmer que la classe UsersService l'appelle correctement. De cette façon, nous pouvons nous assurer que le UsersService fonctionne comme prévu sans avoir à configurer une véritable base de données et un environnement de test.
si tu as un autre façon de faire ou plus optimiser, hésite pas formateur

2023-02-16 08:49 UTC, closed without merging