Feature/user cars
WildCodeSchool/2022-09-Orleans-CDA-Projet-KaraoCar pull request #98
Opened 2023-02-10 14:17 UTC by Ysedda

2023-02-10 21:58 UTC, MGliem requested changes

2023-02-10 21:58 UTC, MGliem commented on package.json
> +    "react-hook-form": "^7.43.0"
pas au bon endroit et on l'a déjà

2023-02-10 21:58 UTC, MGliem commented on apps/frontend/web/src/pages/Home.tsx
> -
Pourquoi avoir touché à ce fichier ? Les imports étaients bien classés et séparé

2023-02-10 21:58 UTC, MGliem commented on apps/frontend/web/src/components/car/CarModal.tsx
> +                ))}
il est possible ici d'edit le html et de rentrer le type que l'on veut.
Ce n'est pas possible avec la hook form de restreindre par rapport à l'objet carTypes ?

2023-02-10 21:58 UTC, MGliem commented on apps/frontend/web/src/components/car/CarModal.tsx
> +                })}
un petit regex pour check que la valeur correspond à une année

2023-02-12 12:41 UTC, Ysedda commented on apps/frontend/web/src/components/car/CarModal.tsx
> +                ))}
Si

2023-02-12 15:46 UTC, MGliem approved these changes

2023-02-13 09:19 UTC, YDrogen requested changes

2023-02-13 09:19 UTC, YDrogen commented on apps/backend/api/src/cars/dto/create-car.dto.ts
> +  photo: string;
C'est pas une autre route pour upload la photo ? Pour la préciser ici ? (Sans vérif en plus :eyes: )

2023-02-13 09:19 UTC, YDrogen commented on apps/backend/api/src/cars/dto/create-car.dto.ts
> +  owner: Partial<User>;
`User` n'est pas un DTO
Le `@ValidateNested` peut être utilisé ici si besoin

2023-02-13 09:19 UTC, YDrogen commented on apps/backend/api/src/entities/index.ts
> +import { Car } from 'src/entities/car.entity';
src

2023-02-13 09:19 UTC, YDrogen commented on apps/frontend/web/src/components/car/Car.tsx
> +            car && car.photo?.includes('blob:')
```suggestion
            car?.photo?.includes('blob:')
```

2023-02-13 09:19 UTC, YDrogen commented on apps/frontend/web/src/components/car/Car.tsx
> +              {car?.brand} - {car?.model}
Attention, si `car` n'est pas défini ça donnera
`undefined - undefined`

2023-02-13 09:19 UTC, YDrogen commented on apps/frontend/web/src/components/car/Car.tsx
> +                    src={'/src/assets/car-icon.svg'}
`/src` ???

2023-02-13 09:19 UTC, YDrogen commented on apps/frontend/web/src/components/car/Car.tsx
> +                    src={'/src/assets/number-icon.svg'}
à changer partout
soit l'image se trouve dans `assets` et est importé comme un component
soit l'image se trouve dans `public` et est linkée par url

2023-02-13 09:19 UTC, YDrogen commented on apps/frontend/web/src/components/car/CarModal.tsx
> +      delete carData.photo;
```suggestion
  const onSubmit = async ({ photo, ...data }: Partial<CarEntity>) => {
    try {
      const carData = { ...data };
```
data ne contient plus photo

2023-02-13 09:19 UTC, YDrogen commented on apps/frontend/web/src/components/car/DeleteDialog.tsx
> +import { Car as CarEntity } from '@apps/backend-api/src/entities/car.entity';
Joli import

2023-02-13 09:19 UTC, YDrogen commented on package.json
> +    "@types/multer": "^1.4.7",
pas au bon endroit j'ai l'impression 🤔

2023-02-13 09:19 UTC, YDrogen commented on apps/frontend/web/src/pages/UserProfile.tsx
> +                          now.getMonth(),
```suggestion
                          now.getMonth() + 1,
```

2023-02-13 10:10 UTC, MGliem approved these changes

2023-02-13 10:21 UTC, YDrogen approved these changes

2023-02-13 10:21 UTC, merged